### PR TITLE
Update minimum node requirements.

### PR DESCRIPTION
**Pull request by haydenyoung**
Running master against nodejs < v10 results in the error:

```
  return (async function * () {
                         ^

SyntaxError: Unexpected token *
```

I cannot impact the node icon at the top of the document; https://img.shields.io/node/v/orbit-db-cli.svg. This would also need to be updated (is this pulling node info from the nodejs package manager?)

### CODE REVIEW

**Comment by haydenyoung** [comment]
Not sure what minimum npm version should be. My minium requirements for running orbitdb cli are npm v6.4.1 with nodejs v10.15.3.

**Comment by aphelionz** [comment]
@RichardLitt Can you help with the question about updating the node.js badge?

**Comment by RichardLitt** [comment]
I believe the node badge gets its info from the package.json `engine` key. I'm not sure if it works for branches; I suspect they don't do that because of the extra computing costs. For now, I see no reason this shouldn't be merged.

**Comment by haydenyoung** [comment]
@RichardLitt is it possible the node version is being picked up from https://www.npmjs.com/package/orbit-db-cli?

**Comment by aphelionz** [comment]
Feel free to carry on the discussion here or on Gitter, but LGTM. The badge still didn't update but I'm relatively confident an `npm publish` will do the trick.

**Pull request merged**
